### PR TITLE
Python rastersource

### PR DESCRIPTION
**Pull request by vpipkt**
With tests.

One comment is i used PDS landsat in the python tests rather than trying to use local jar files, or files in the local path of the python package. Test execution time is about 30s on my machine.

### CODE REVIEW

**Comment by vpipkt** [comment]
Also, should this target s22s/develop or locationtech/develop?

**Review by metasim — COMMENTED** [review]
🙇 🙏

**Comment by metasim** [comment]
Next time do `locationtech/rasterframes`.

**Comment by metasim** [comment]
Next PR let's try to patch `spark.read` to have a `rastersource` method/field to automatically set the format and expose relevant option functions, just like in Scala.

https://github.com/locationtech/rasterframes/blob/develop/datasource/src/main/scala/org/locationtech/rasterframes/datasource/rastersource/package.scala#L36

**Pull request merged**
